### ISSUE TITLE
openvpn doesn't connect

### ISSUE THREAD

**Issue by micsuka** [CyanogenDefy/android_device_motorola_jordan#25]
I've installed the cm7-110625-1657-NIGHTLY and the openvpn doesn't connect.
Apparently the openvpn binary exits, does anybody know how to debug this?
The logcat is below:

I/keystore( 1935): uid: 1000 action: t -> 1 state: 1 -> 1 retry: 4
D/VpnManager( 5905): succeeded to connect to VPN service
D/com.android.settings.vpn.AuthenticationActor( 5905): ~~~~~~ connect() succeeded!
W/InputManagerService( 2138): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@40959ad0
D/VpnSettings( 5905): received connectivity: micsaek.ro: connected? CONNECTING   err=0
I/SProxy_mtpd( 5766): Stop VPN daemon: mtpd
D/SProxy_mtpd( 5766): mtpd is stopped after 0 msec
D/SProxy_mtpd( 5766): stopping mtpd, success? true
I/SProxy_racoon( 5766): Stop VPN daemon: racoon
D/SProxy_racoon( 5766): racoon is stopped after 0 msec
D/SProxy_racoon( 5766): stopping racoon, success? true
D/VpnService( 5766):   Local IP: 192.168.1.70, if: tiwlan0
D/VpnService( 5766):        VPN UP: down
I/SProxy_mtpd( 5766): Start VPN daemon: mtpd
D/SProxy_mtpd( 5766): mtpd is running after 0 msec
D/SProxy_mtpd( 5766): service not yet listen()ing; try again
D/mtpd    ( 5997): Waiting for control socket
D/mtpd    ( 5997): Received 33 arguments
I/mtpd    ( 5997): Using protocol openvpn
I/mtpd    ( 5997): Starting openvpn (pppox = -1)
I/mtpd    ( 5997): openvpn started (pid = 5998)
I/SProxy_mtpd( 5766): got data from control socket: 33
I/mtpd    ( 5997): Received signal 17
I/mtpd    ( 5997): Pppd is terminated (status = 1)
I/mtpd    ( 5997): Mtpd is terminated (status = 33)
D/dalvikvm( 3121): GC_EXPLICIT freed 11K, 50% free 2726K/5379K, external 0K/0K, paused 58ms
E/VpnService( 5766): onError()
E/VpnService( 5766): java.io.IOException: No such file or directory
E/VpnService( 5766):    at android.net.LocalSocketImpl.connectLocal(Native Method)
E/VpnService( 5766):    at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:238)
E/VpnService( 5766):    at android.net.LocalSocket.connect(LocalSocket.java:98)
E/VpnService( 5766):    at com.android.server.vpn.OpenvpnService$OpenvpnThread.openSocket(OpenvpnService.java:247)
E/VpnService( 5766):    at com.android.server.vpn.OpenvpnService$OpenvpnThread.<init>(OpenvpnService.java:194)
E/VpnService( 5766):    at com.android.server.vpn.OpenvpnService.waitUntilConnectedOrTimedout(OpenvpnService.java:149)
E/VpnService( 5766):    at com.android.server.vpn.VpnService.onConnect(VpnService.java:148)
E/VpnService( 5766):    at com.android.server.vpn.VpnServiceBinder$2.run(VpnServiceBinder.java:118)
E/VpnService( 5766):    at java.lang.Thread.run(Thread.java:1019)
I/VpnService( 5766): disconnecting VPN...
D/VpnSettings( 5905): received connectivity: micsaek.ro: connected? DISCONNECTING   err=0
D/VpnService( 5766): onFinalCleanUp()
I/VpnService( 5766): restore original suffices --> null

**Comment by krejcipetr** [comment]
Same case. I didn't find what is wrong.
